version: "3.9"

volumes:
    prometheus_data: {}
    grafana_data: {}
    pgdb:

networks:
  back-tier:

services:

  go:
    build: ./go
    ports:
      - "8080:8080"
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - go
    networks:
      - back-tier
    restart: always
    
  redis:
    image: redis
    networks:
     - back-tier

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
     - pgdb:/var/lib/postgresql/data
    networks:
     - back-tier

  sentry:
    image: sentry
    links:
     - redis
     - postgres
    ports:
     - 9010:9000
    networks:
     - back-tier
    environment:
      SENTRY_SECRET_KEY: 'AAAAAAAAAAAAAAAAAAAAQQQQQQQQQQQQ'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

  cron:
    image: sentry
    links:
     - redis
     - postgres
    networks:
     - back-tier 
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: 'AAAAAAAAAAAAAAAAAAAAQQQQQQQQQQQQ'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

  worker:
    image: sentry
    links:
     - redis
     - postgres
    networks:
     - back-tier 
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: 'AAAAAAAAAAAAAAAAAAAAQQQQQQQQQQQQ'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis    